function update_windfield_name(wfile,SimulinkModel)
% % Changes current wind profile data (if possible)
l = load([wfile '.mat']);                                                                                                                                                                                                                                                                                                                                         
p = get_param([SimulinkModel '/Wind Field/Ambient Field'],'UserData');                                                                                                                                                                                                                                                                                                                

% % Check for correct wind field type                                                                                                                                                                                                                                                                                                                             
if(isfield(l.wind,'ambient_wind'))                                                                                                                                                                                                                                                                                                                             
    errordlg('It is not the correct wind field type. Probably a no_taylor type wind field. See create_windfield()','Wind field invalid')                                                                                                                                                                                                                       
   return                                                                                                                                                                                                                                                                                                                                                      
end                                                                                                                                                                                                                                                                                                                                                            

% % Check for compatible wind field                                                                                                                                                                                                                                                                                                                               
% % if (~isequal(p.grid,l.wind.grid))                                                                                                                                                                                                                                                                                                                              
% %     str_grids = sprintf('\n            Model     New wind \n size          %d         %d \n xsize       %d       %d \n ysize        %d      %d \n Try to type: help create_windfield',p.grid.size, l.wind.grid.size, p.grid.xsize, l.wind.grid.xsize, p.grid.ysize, l.wind.grid.ysize);                                                                        
% %     errordlg(['The wind fields must have the same grid' str_grids],'Wind field Error')                                                                                                                                                                                                                                                                         
% %    return                                                                                                                                                                                                                                                                                                                                                      
% % end                                                                                                                                                                                                                                                                                                                                                            

% % If the wind field is too short, reset the simulation time 
if strcmp(get_param(bdroot,'StopTime'),'tMax') ~= 1
    if(p.SimTime < eval(get_param(bdroot,'StopTime')))                                                                                                                                                                                                                                                                                                             
        warndlg('The model simulation time is longer than windfield. Resetting model simulation time')                                                                                                                                                                                                                                                             
        set_param(bdroot,'StopTime',num2str(p.SimTime))                                                                                                                                                                                                                                                                                                            
    end
end

% % Change wf sample time                                                                                                                                                                                                                                                                                                                                         
set_param([SimulinkModel '/Wind Field/CTrate'],'OutPortSampleTime',num2str(l.wind.Ts))                                                                                                                                                                                                                                                                                              

% % Add old turbine position data                                                                                                                                                                                                                                                                                                                                 
l.wind.xgrids=p.xgrids;                                                                                                                                                                                                                                                                                                                                        

% % Save the new parameters                                                                                                                                                                                                                                                                                                                                       
set_param([SimulinkModel '/Wind Field/Ambient Field'],'UserData',l.wind);   
end